# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python Package Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the new version (e.g., 1.2.1)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Set new version
        run: echo "NEW_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Update version in setup.py
        run: |
          echo "New version is $NEW_VERSION"
          sed -i'' -e "s/^VERSION = .*/VERSION = '$NEW_VERSION'/" setup.py

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Create and push new tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$NEW_VERSION" -m "Release version v$NEW_VERSION"
          git push origin "v$NEW_VERSION"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v$NEW_VERSION"
          release_name: Release v$NEW_VERSION
          draft: false
          prerelease: false

      - name: Upload Wheel File to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/AlLoRa-${{ env.NEW_VERSION }}-py3-none-any.whl
          asset_name: AlLoRa-${{ env.NEW_VERSION }}-py3-none-any.whl
          asset_content_type: application/octet-stream


      - name: Publish package to TestPyPI
        if: github.event.inputs.version != ''
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
